# This is a basic workflow to help you get started with Acti

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Crear archivo de prueba
        run: echo "Hola desde CI" > saludo.txt

      - name: Subir como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: saludo
          path: saludo.txt

